### ISSUE TITLE
Close dropdown on tab

### ISSUE THREAD

**Issue by stil4m** [inkuzmin/elm-multiselect#7]
Currently, the dropdown does not respond to the TAB character. The browser just moves the cursor to the next input element. Would it be a good idea to close the dropdown when the user hits the TAB key? 

I'm willing to create a PR for this, while you already did the awesome work by creating this package. Let me know if you like the functionality.

**Comment by inkuzmin** [comment]
@stil4m that's great idea!

**Comment by stil4m** [comment]
Created a [PR](https://github.com/inkuzmin/elm-multiselect/pull/8)

**Comment by inkuzmin** [comment]
Thanks! You may want to check the part I [modified](https://github.com/inkuzmin/elm-multiselect/commit/4ef68309ded7c8dc1e7709dcd971503bccf6b0cf#diff-87f511757043e9ba5fb070be0789a37aL475) – I split the highlighted expression, because `protected` has to be set to `True` for `Esc` only, otherwise input will stop responding to click.
